"""Pure helpers for replying to a proactive slow-query offer.

Kept free of Bot Framework / Azure imports so the yes/no classification and the
grounded-prompt construction can be unit tested with plain dicts.
"""
import time

_AFFIRMATIVE = {
    "yes", "y", "yeah", "yep", "yup", "sure", "ok", "okay", "please",
    "yes please", "help", "yes help", "go ahead", "do it", "sounds good",
}
_NEGATIVE = {
    "no", "n", "nope", "nah", "no thanks", "no thank you", "not now",
    "later", "maybe later",
}


def _normalize(text: str) -> str:
    return (text or "").strip().lower().rstrip("!. ")


def is_affirmative(text: str) -> bool:
    normalized = _normalize(text)
    return normalized in _AFFIRMATIVE or normalized.startswith("yes")


def is_negative(text: str) -> bool:
    return _normalize(text) in _NEGATIVE


def pending_expired(pending: dict) -> bool:
    expires_at = pending.get("expiresAt")
    return bool(expires_at) and time.time() > int(expires_at)


def grounded_prompt(pending: dict) -> str:
    """Turn a stored offending-query context into an analysis prompt that is
    grounded in that query.

    ``EventText`` is the DAX **auto-generated by the Power BI engine** for a report
    visual — not a query the user hand-wrote. The prompt therefore frames it as
    evidence of the measures, columns and groupings the user was after, rather than
    as user-authored DAX to be critiqued line by line."""
    model = pending.get("model") or "the semantic model"
    report = pending.get("report")
    source = f"the '{report}' report and " if report else ""
    duration_ms = pending.get("durationMs")
    duration = f"{int(duration_ms) / 1000:.1f}s" if duration_ms else "an extended time"
    event_text = (pending.get("eventText") or "").strip()
    return (
        f"A slow Power BI query (took {duration}) was captured from {source}the "
        f"'{model}' semantic model.\n\n"
        "IMPORTANT: The query below is the DAX that the Power BI engine "
        "auto-generated for a report visual — it is NOT a query the user wrote by "
        "hand. Do not treat it as the user's literal query or critique its DAX style. "
        "Instead, read it as evidence of what the user was trying to do: the measures "
        "they selected, the columns/fields they grouped or filtered by, and the shape "
        "of the visual. Use that as the starting point.\n\n"
        "Then give concrete, actionable guidance to speed it up. Ground your "
        "analysis in the measures, columns and relationships this query touches — do "
        "not scan the entire model or review unrelated tables and measures. Focus on "
        "the semantic model (measure definitions, column cardinality/data types, "
        "relationships, aggregations) and, where relevant, how the report visual could "
        "be adjusted, so that the user's intended result returns faster.\n\n"
        "Engine-generated DAX (starting point, from EventText):\n```\n"
        + event_text
        + "\n```"
    )
